export const activeSubscriptionType = {
  object: 'list',
  data: [
    {
      id: 'sub_1N7cwLIW91ghbnFjNfnPwppH',
      object: 'subscription',
      application: null,
      application_fee_percent: null,
      automatic_tax: [Object],
      billing_cycle_anchor: Math.floor(Date.now() / 1000),
      billing_thresholds: null,
      cancel_at: null,
      cancel_at_period_end: false,
      canceled_at: null,
      cancellation_details: [Object],
      collection_method: 'charge_automatically',
      created: Math.floor(Date.now() / 1000),
      currency: 'usd',
      current_period_end: Math.floor(Date.now() / 1000) + 365 * 24 * 60 * 60,
      current_period_start: Math.floor(Date.now() / 1000),
      customer: 'cus_NuCKS9RdNr5wFR',
      days_until_due: null,
      default_payment_method: 'pm_1N91psIW91ghbnFjSjsumDr1',
      default_source: null,
      default_tax_rates: [],
      description: null,
      discount: null,
      ended_at: null,
      items: [Object],
      latest_invoice: 'in_1N91rJIW91ghbnFj8CzvEME9',
      livemode: false,
      metadata: {},
      next_pending_invoice_item_invoice: null,
      on_behalf_of: null,
      pause_collection: null,
      payment_settings: [Object],
      pending_invoice_item_interval: null,
      pending_setup_intent: null,
      pending_update: null,
      plan: [Object],
      quantity: 1,
      schedule: null,
      start_date: Math.floor(Date.now() / 1000),
      status: 'active',
      test_clock: null,
      transfer_data: null,
      trial_end: null,
      trial_settings: [Object],
      trial_start: null,
    },
  ],
  has_more: false,
  url: '/v1/subscriptions',
};
