export const sessionTestType = {
  id: 'cs_test_a1oPmhIhfTC4MMonYARDeQfm9PzguRN0Ammc8YK9q0TAcHODJZp0tQGh41',
  object: 'checkout.session',
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 1000,
  amount_total: 1000,
  automatic_tax: { enabled: false, status: null },
  billing_address_collection: null,
  cancel_url: 'http://localhost:3000/profile/settings/edit?success=false',
  client_reference_id: null,
  consent: null,
  consent_collection: null,
  created: Math.floor(Date.now() / 1000),
  currency: 'usd',
  currency_conversion: null,
  custom_fields: [],
  custom_text: { shipping_address: null, submit: null },
  customer: 'cus_NuCKS9RdNr5wFR',
  customer_creation: null,
  customer_details: {
    address: null,
    email: 'admin@admin.com',
    name: null,
    phone: null,
    tax_exempt: 'none',
    tax_ids: null,
  },
  customer_email: null,
  expires_at: Math.floor(Date.now() / 1000) + 30 * 60,
  invoice: null,
  invoice_creation: null,
  livemode: false,
  locale: null,
  metadata: {},
  mode: 'subscription',
  payment_intent: null,
  payment_link: null,
  payment_method_collection: 'always',
  payment_method_options: null,
  payment_method_types: ['card'],
  payment_status: 'unpaid',
  phone_number_collection: { enabled: false },
  recovered_from: null,
  setup_intent: null,
  shipping_address_collection: null,
  shipping_cost: null,
  shipping_details: null,
  shipping_options: [],
  status: 'open',
  submit_type: null,
  subscription: null,
  success_url: 'http://localhost:3000/profile/settings/edit?success=true',
  total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
  url: 'https://checkout.stripe.com/c/pay/cs_test_a1oPmhIhfTC4MMonYARDeQfm9PzguRN0Ammc8YK9q0TAcHODJZp0tQGh41#fidkdWxOYHwnPyd1blpxYHZxWjA0SGFHQl9MUjw0Ym1na0NvUm9%2FdG9CM0g3T0RhMTU8MElwajEzaDZMU2R1UkZqc1ZXdHFPblViNjBva25VbVR8SjdjaTJ3ckl0cXN3VVd3cVJLdGZBQUdJNTVRSUAzVUk1YycpJ2N3amhWYHdzYHcnP3F3cGApJ2lkfGpwcVF8dWAnPyd2bGtiaWBabHFgaCcpJ2BrZGdpYFVpZGZgbWppYWB3dic%2FcXdwYHgl',
};

export const sessionTestType2 = {
  id: 'cs_test_e1oPmhIhfTC4MMonYARDeQfm9PzguRN0Ammc8YK9q0TAcHODJZp0tQGh41',
  object: 'checkout.session',
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 10000,
  amount_total: 10000,
  automatic_tax: { enabled: false, status: null },
  billing_address_collection: null,
  cancel_url: 'http://localhost:3000/profile/settings/edit?success=false',
  client_reference_id: null,
  consent: null,
  consent_collection: null,
  created: Math.floor(Date.now() / 1000),
  currency: 'usd',
  currency_conversion: null,
  custom_fields: [],
  custom_text: { shipping_address: null, submit: null },
  customer: 'cus_NuCKS9RdNr5wFR',
  customer_creation: null,
  customer_details: {
    address: null,
    email: 'admin@admin.com',
    name: null,
    phone: null,
    tax_exempt: 'none',
    tax_ids: null,
  },
  customer_email: null,
  expires_at: Math.floor(Date.now() / 1000) + 30 * 60,
  invoice: null,
  invoice_creation: null,
  livemode: false,
  locale: null,
  metadata: {},
  mode: 'subscription',
  payment_intent: null,
  payment_link: null,
  payment_method_collection: 'always',
  payment_method_options: null,
  payment_method_types: ['card'],
  payment_status: 'unpaid',
  phone_number_collection: { enabled: false },
  recovered_from: null,
  setup_intent: null,
  shipping_address_collection: null,
  shipping_cost: null,
  shipping_details: null,
  shipping_options: [],
  status: 'open',
  submit_type: null,
  subscription: null,
  success_url: 'http://localhost:3000/profile/settings/edit?success=true',
  total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
  url: 'https://checkout.stripe.com/c/pay/cs_test_e1oPmhIhfTC4MMonYARDeQfm9PzguRN0Ammc8YK9q0TAcHODJZp0tQGh41#fidkdWxOYHwnPyd1blpxYHZxWjA0SGFHQl9MUjw0Ym1na0NvUm9%2FdG9CM0g3T0RhMTU8MElwajEzaDZMU2R1UkZqc1ZXdHFPblViNjBva25VbVR8SjdjaTJ3ckl0cXN3VVd3cVJLdGZBQUdJNTVRSUAzVUk1YycpJ2N3amhWYHdzYHcnP3F3cGApJ2lkfGpwcVF8dWAnPyd2bGtiaWBabHFgaCcpJ2BrZGdpYFVpZGZgbWppYWB3dic%2FcXdwYHgl',
};
