export const checkoutSessionCompletedForTestSubscription = {
  id: 'evt_1N7cx3IW91ghbnFj83zN1DMJ',
  data: {
    object: {
      id: 'cs_test_a1oPmhIhfTC4MMonYARDeQfm9PzguRN0Ammc8YK9q0TAcHODJZp0tQGh41',
      url: null,
      mode: 'subscription',
      locale: null,
      object: 'checkout.session',
      status: 'complete',
      consent: null,
      created: Math.floor(Date.now() / 1000), //
      invoice: 'in_1N7cwLIW91ghbnFjV2Fsb78c',
      currency: 'usd',
      customer: 'cus_NuCKS9RdNr5wFR',
      livemode: false,
      metadata: {},
      cancel_url: 'http://localhost:3000/profile/settings/edit?success=false',
      expires_at: Math.floor(Date.now() / 1000) + 10 * 60,
      custom_text: {
        submit: null,
        shipping_address: null,
      },
      submit_type: null,
      success_url: 'http://localhost:3000/profile/settings/edit?success=true',
      amount_total: 1000,
      payment_link: null,
      setup_intent: null,
      subscription: 'sub_1N7cwLIW91ghbnFjNfnPwppH',
      automatic_tax: {
        status: null,
        enabled: false,
      },
      custom_fields: [],
      shipping_cost: null,
      total_details: {
        amount_tax: 0,
        amount_discount: 0,
        amount_shipping: 0,
      },
      customer_email: null,
      payment_intent: null,
      payment_status: 'paid',
      recovered_from: null,
      amount_subtotal: 1000,
      after_expiration: null,
      customer_details: {
        name: 'uJIb9I',
        email: 'iamdemos461@gmail.com',
        phone: null,
        address: {
          city: null,
          line1: null,
          line2: null,
          state: null,
          country: 'BY',
          postal_code: null,
        },
        tax_ids: [],
        tax_exempt: 'none',
      },
      invoice_creation: null,
      shipping_details: null,
      shipping_options: [],
      customer_creation: null,
      consent_collection: null,
      client_reference_id: null,
      currency_conversion: null,
      payment_method_types: ['card'],
      allow_promotion_codes: null,
      payment_method_options: null,
      phone_number_collection: {
        enabled: false,
      },
      payment_method_collection: 'always',
      billing_address_collection: null,
      shipping_address_collection: null,
    },
  },
  type: 'checkout.session.completed',
  object: 'event',
  created: Math.floor(Date.now() / 1000) + 30 * 60,
  request: {
    id: null,
    idempotency_key: null,
  },
  livemode: false,
  api_version: '2022-11-15',
  pending_webhooks: 2,
};

export const checkoutSessionCompleted2 = {
  id: 'evt_1N7cx3IW91ghbnFj83zN1DEJ',
  data: {
    object: {
      id: 'cs_test_e1oPmhIhfTC4MMonYARDeQfm9PzguRN0Ammc8YK9q0TAcHODJZp0tQGh41',
      url: null,
      mode: 'subscription',
      locale: null,
      object: 'checkout.session',
      status: 'complete',
      consent: null,
      created: Math.floor(Date.now() / 1000), //
      invoice: 'in_1N7cwLIW91ghbnFjV2Fsb78c',
      currency: 'usd',
      customer: 'cus_NuCKS9RdNr5wFR',
      livemode: false,
      metadata: {},
      cancel_url: 'http://localhost:3000/profile/settings/edit?success=false',
      expires_at: Math.floor(Date.now() / 1000) + 10 * 60,
      custom_text: {
        submit: null,
        shipping_address: null,
      },
      submit_type: null,
      success_url: 'http://localhost:3000/profile/settings/edit?success=true',
      amount_total: 10000,
      payment_link: null,
      setup_intent: null,
      subscription: 'sub_1E7cwLIW91ghbnFjNfnPwppH',
      automatic_tax: {
        status: null,
        enabled: false,
      },
      custom_fields: [],
      shipping_cost: null,
      total_details: {
        amount_tax: 0,
        amount_discount: 0,
        amount_shipping: 0,
      },
      customer_email: null,
      payment_intent: null,
      payment_status: 'paid',
      recovered_from: null,
      amount_subtotal: 10000,
      after_expiration: null,
      customer_details: {
        name: 'uJIb9I',
        email: 'iamdemos461@gmail.com',
        phone: null,
        address: {
          city: null,
          line1: null,
          line2: null,
          state: null,
          country: 'BY',
          postal_code: null,
        },
        tax_ids: [],
        tax_exempt: 'none',
      },
      invoice_creation: null,
      shipping_details: null,
      shipping_options: [],
      customer_creation: null,
      consent_collection: null,
      client_reference_id: null,
      currency_conversion: null,
      payment_method_types: ['card'],
      allow_promotion_codes: null,
      payment_method_options: null,
      phone_number_collection: {
        enabled: false,
      },
      payment_method_collection: 'always',
      billing_address_collection: null,
      shipping_address_collection: null,
    },
  },
  type: 'checkout.session.completed',
  object: 'event',
  created: Math.floor(Date.now() / 1000) + 30 * 60,
  request: {
    id: null,
    idempotency_key: null,
  },
  livemode: false,
  api_version: '2022-11-15',
  pending_webhooks: 2,
};

const ev = {
  id: 'cs_test_a1x3E6KcBCaIS8towoXjlDIlVAdoLmxs9UbSJ5xdzVFCgAo2e5mMuPygUi',
  object: 'checkout.session',
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 10000,
  amount_total: 10000,
  automatic_tax: { enabled: false, status: null },
  billing_address_collection: null,
  cancel_url: 'http://localhost:3000/profile/settings/edit?success=false',
  client_reference_id: null,
  consent: null,
  consent_collection: null,
  created: 1684397205,
  currency: 'usd',
  currency_conversion: null,
  custom_fields: [],
  custom_text: { shipping_address: null, submit: null },
  customer: 'cus_NurYgx3v4huJrf',
  customer_creation: null,
  customer_details: {
    address: {
      city: null,
      country: 'PL',
      line1: null,
      line2: null,
      postal_code: null,
      state: null,
    },
    email: 'admin@admin.com',
    name: 'Takomas',
    phone: null,
    tax_exempt: 'none',
    tax_ids: [],
  },
  customer_email: null,
  expires_at: 1684399005,
  invoice: 'in_1N91rJIW91ghbnFj8CzvEME9',
  invoice_creation: null,
  livemode: false,
  locale: null,
  metadata: {},
  mode: 'subscription',
  payment_intent: null,
  payment_link: null,
  payment_method_collection: 'always',
  payment_method_options: null,
  payment_method_types: ['card'],
  payment_status: 'paid',
  phone_number_collection: { enabled: false },
  recovered_from: null,
  setup_intent: null,
  shipping_address_collection: null,
  shipping_cost: null,
  shipping_details: null,
  shipping_options: [],
  status: 'complete',
  submit_type: null,
  subscription: 'sub_1N91rJIW91ghbnFjkavrDPLM',
  success_url: 'http://localhost:3000/profile/settings/edit?success=true',
  total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
  url: null,
};
